INSERT INTO ALUMNOS (NOM, COGNOMS, DATA_ALTA) VALUES ('Joan', 'Petit', '2020-12-21');
INSERT INTO ALUMNOS (NOM, COGNOMS, DATA_ALTA) VALUES ('Joana', 'Petita', '2021-12-21');
INSERT INTO ALUMNOS (NOM, COGNOMS, DATA_ALTA) VALUES ('Gegant', 'Nobita', '2020-12-01');